### PR TITLE
Fix missing set_coef call for user inflow condition

### PR DESCRIPTION
**Pull request by vbaconnet**
Put the call to `bc_inflow%set_coef` back in fluid scheme that was causing `usr_inflow::usr_inflow_validate` to fail when running with a `"user"` inflow condition since the `usr_inflow_t%c` pointer was never being associated.

### CODE REVIEW

**Review by njansson — APPROVED** [review]

**Comment by timofeymukha** [comment]
Guys, let's wait for the varprops pr to merge in, so that we don't have to fix the linter for the fluid scheme in 2 PRs.

**Comment by timofeymukha** [comment]
@vbaconnet The `bc_t` type now contains the `coef_t`, you see it being passed in `call this%bc_inflow%init_base(this%c_Xh)`.

So, the correct thing to do here is to kill the additional coef pointer in the user inflow type, and directly use the one in parent type. The fluid_scheme_t code I think can remain as is.

**Comment by vbaconnet** [comment]
Ok so I guess don't merge until #1351 is merged @timofeymukha ?

**Comment by timofeymukha** [comment]
> Ok so I guess don't merge until #1351 is merged @timofeymukha ?

I guess if you only have to modify the usr_inflow_t then we can merge independently.

**Review by timofeymukha — APPROVED** [review]

**Pull request merged**
