### PR TITLE
Adds output control "never" and throw for non-positive nsamples

### PR DESCRIPTION
**Pull request by timofeymukha**
* Adds `never` as an option for the `time_based_controller`.  Useful for benchmarking or having a simcomp do no output, for example.
* Forces `nsamples` to be positive.

### CODE REVIEW

**Review by njansson — APPROVED** [review]
Approved, but one question, will this still allow me to prevent sampling, but perform the simcomps? I can foresee that one would like to skip outputs, but do the components during benchmarking?

**Comment by timofeymukha** [comment]
If I understand you correctly then yes, because computing and outputting have serparate controllers. So you would do something like.
```json
{
"output_control": "never",
"compute_control": "tsteps",
"compute_value": 1
}
```

**Comment by njansson** [comment]
> If I understand you correctly then yes, because computing and outputting have serparate controllers. So you would do something like.
> 
> ```json
> {
> "output_control": "never",
> "compute_control": "tsteps",
> "compute_value": 1
> }
> ```

True, since it's an own time-controller and now global as for some reason thought

**Comment by timofeymukha** [comment]
Rayleigh in reframe has nsamples 0 :P.

**Comment by timofeymukha** [comment]
Added an if-branch in case.f90 to set output_value to 0.0 (a dummy value) when output_control for fluid is "never"

**Review by njansson — APPROVED** [review]

**Pull request merged**
