### PR TITLE
Cleanup of bdf_time_scheme_t; adding its docs and tests

### LINKED ISSUE #114: Abstract BDF type
In order to be able to use different BDF schemes a new BDF type is necessary with subroutines such as 'bdf%apply'

### PR DESCRIPTION
**Pull request by timofeymukha**
- The computation of the coeffs for the BDF scheme no longer uses a messy linear solver. Instead, they are computed using explicit formulas, taken from a [technical note by Nishikawa](https://www.researchgate.net/publication/351082535_Derivation_of_BDF2BDF3_for_Variable_Step_Size). 
- The above fixes the maximum order to 3, which anyway is the maximum used. 
- However, we can easily extend to higher order later if we want, because the subroutine `fd_weights_full` that we have can be used to compute the coefficients for arbitrary order. I am surprised Nek5000 did not use that, actually! It requires a bit of array reordering, etc, so for now I went for the explicit formulas.
- Quite detailed documentation for the BDF scheme is provided. There are two somewhat surprising conventions one should be aware of.
- Added tests for constant and variable dt cases.

I would say this closes #114 for now.

### CODE REVIEW

**Comment by timofeymukha** [comment]
Well, that's unfortunate. @njansson can I somehow see exactly what fails in the test?

**Comment by njansson** [comment]
> Well, that's unfortunate. @njansson can I somehow see exactly what fails in the test?

Unfortunately not, via GitHub you can only see which test failed, but we don't keep any of the more detailed logs (which we should fix...)

I would rerunning the tests locally on check what breaks.

**Comment by njansson** [comment]
> By the way, the old messy implementation is moved to the test file, so that we can use it to test the new stuff.

Given the discussions we had earlier in #114, can't we just fix the dimensions to 3 or similar?

**Comment by timofeymukha** [comment]
> > By the way, the old messy implementation is moved to the test file, so that we can use it to test the new stuff.
> 
> Given the discussions we had earlier in #114, can't we just fix the dimensions to 3 or similar?

Yes, makes sense, particularly since `rhs_maker`s kernels are hard-coded to take 3 values.

**Comment by timofeymukha** [comment]
Let's see if our new action works :-)

**Comment by timofeymukha** [comment]
It's still the old yaml file :-(. @njansson do we actually have to merge the yaml to master?

**Comment by njansson** [comment]
> It's still the old yaml file :-(. @njansson do we actually have to merge the yaml to master?

It uses the develop yaml of the to be merged branch, thus you need to cherry pick the changes into this branch

**Comment by timofeymukha** [comment]
image

**Review by njansson — APPROVED** [review]

**Pull request merged**
