### PR TITLE
Update indentation of logs

### PR DESCRIPTION
**Pull request by timfelle**
Ensure the neko header is not indented.

Reduce the log default indentation to 0 instead of the entire log being indented by 1 space.

### CODE REVIEW

**Comment by timofeymukha** [comment]
Makes sense, I guess. Was there some reason to start with a space?

**Review by timofeymukha — APPROVED** [review]

**Comment by timfelle** [comment]
> Makes sense, I guess. Was there some reason to start with a space?

The header had an additionaly space added for some wiered reason that i could not figure out. `write (*,*)` prepends a space `write (*,'(A)')` did not.
I expect the extra space in the logger was to make it consistent with the header.

**Comment by njansson** [comment]
The space is added by Fortran, so a reason to keep it would be that user added write statement wouldn't be too far off

**Comment by timfelle** [comment]
> The space is added by Fortran, so a reason to keep it would be that user added write statement wouldn't be too far off  

Lets close it then

**Pull request closed without merging**
