### PR TITLE
Feature/Device count

### PR DESCRIPTION
**Pull request by timfelle**
Adding a unified interface to get the number of available backend devices.

In PR #1358 it was mentioned this could be used to move the check out of initialization. Where should that be done then?

### CODE REVIEW

**Comment by njansson** [comment]
Isn't the indentation for new line a bit off, now we have a several fixes which is not what eMacs Fortran mode (which we follow) gives ?

**Comment by timofeymukha** [comment]
Is there a comprehensive ruleset of eMacs Fortran mode written somewhere when it comes to indentation after &?

**Comment by timofeymukha** [comment]
@timfelle regarding the check location, maybe somewhere in the beginning of neko_init ?

**Comment by timfelle** [comment]
I have looked into the line continuation. Judging from https://emacsdocs.org/docs/emacs/Fortran-Indent
It seem the continuation lines must be indented by 5 additional space compared to the current context.

Is that what we should follow @njansson? Because then i will update the documentation to reflect that.

**Comment by njansson** [comment]
> I have looked into the line continuation. Judging from https://emacsdocs.org/docs/emacs/Fortran-Indent It seem the continuation lines must be indented by 5 additional space compared to the current context.
> 
> Is that what we should follow @njansson? Because then i will update the documentation to reflect that.

I would say yes. It also makes it consistent with most of the continuation lines in Neko then, which followed their style.

**Comment by timfelle** [comment]
Done, @njansson and @timofeymukha 
However, Depends on #1391 to be merged

**Review by njansson — APPROVED** [review]

**Comment by njansson** [comment]
@timfelle Should we merge this one?

**Comment by timfelle** [comment]
> @timfelle Should we merge this one?

Should be good yes

**Pull request merged**
