### PR TITLE
Add instructions to run Neko using the Docker container

### LINKED ISSUE #993: Add running from the Gitlab docker file to user manual
An additional alternative to quickly test the code.

### PR DESCRIPTION
**Pull request by timofeymukha**
Closes #993

### CODE REVIEW

**Comment by timofeymukha** [comment]
If someone gives the instructions a shot, to double-check they work, it'd be great!

**Review by njansson — APPROVED** [review]

**Comment by vbaconnet** [comment]
Throwing EOF error for me when running on WSL with `docker run --rm -v /mnt/c/Users/victo/Documents/KTH/neko/neko/examples/2d_cylinder:/case 6a9febfaa645 bin/bash -c "cd /case && neko 2d_cylinder.case"`

```

    _  __  ____  __ __  ____
   / |/ / / __/ / //_/ / __ \
  /    / / _/  / ,<   / /_/ /
 /_/|_/ /___/ /_/|_|  \____/

 (version: 0.6.1)
 (build: 2023-07-19 on x86_64-pc-linux-gnu using gnu)


 -------Job Information--------
 Start time: 03:06 / 2023-11-03
 Running on: 1 MPI rank
 CPU type  : Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
 Bcknd type: CPU
 Real type : double precision

 -------------Case-------------
 Reading case file 2d_cylinder.case
At line 118 of file case.f90 (unit = 10, file = '2d_cylinder.case')
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x7feb755d0d21 in ???
#1  0x7feb755d1869 in ???
#2  0x7feb755d254f in ???
#3  0x7feb75815c5b in ???
#4  0x7feb75816f3c in ???
#5  0x7feb75819a9e in ???
#6  0x7feb75819d0c in ???
#7  0x7feb75819e67 in ???
#8  0x559600f9f836 in __case_MOD_case_init
        at /tmp/root/spack-stage/spack-stage-neko-0.6.1-r6n3ghz5aokgqhz2yry6ddsyeg3vcyhc/spack-src/src/case.f90:118
#9  0x559601003dce in __neko_MOD_neko_init
        at /tmp/root/spack-stage/spack-stage-neko-0.6.1-r6n3ghz5aokgqhz2yry6ddsyeg3vcyhc/spack-src/src/neko.f90:207
#10  0x559601004f9d in turboneko
        at /tmp/root/spack-stage/spack-stage-neko-0.6.1-r6n3ghz5aokgqhz2yry6ddsyeg3vcyhc/spack-src/src/driver.f90:6
#11  0x559600eaa80e in main
        at /tmp/root/spack-stage/spack-stage-neko-0.6.1-r6n3ghz5aokgqhz2yry6ddsyeg3vcyhc/spack-src/src/driver.f90:3
```

**Comment by njansson** [comment]
> Throwing EOF error for me when running on WSL with `docker run --rm -v /mnt/c/Users/victo/Documents/KTH/neko/neko/examples/2d_cylinder:/case 6a9febfaa645 bin/bash -c "cd /case && neko 2d_cylinder.case"`
> 
> ```
> 
>     _  __  ____  __ __  ____
>    / |/ / / __/ / //_/ / __ \
>   /    / / _/  / ,<   / /_/ /
>  /_/|_/ /___/ /_/|_|  \____/
> 
>  (version: 0.6.1)
>  (build: 2023-07-19 on x86_64-pc-linux-gnu using gnu)
> 
> 
>  -------Job Information--------
>  Start time: 03:06 / 2023-11-03
>  Running on: 1 MPI rank
>  CPU type  : Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
>  Bcknd type: CPU
>  Real type : double precision
> 
>  -------------Case-------------
>  Reading case file 2d_cylinder.case
> At line 118 of file case.f90 (unit = 10, file = '2d_cylinder.case')
> Fortran runtime error: End of file
> 
> Error termination. Backtrace:
> #0  0x7feb755d0d21 in ???
> #1  0x7feb755d1869 in ???
> #2  0x7feb755d254f in ???
> #3  0x7feb75815c5b in ???
> #4  0x7feb75816f3c in ???
> #5  0x7feb75819a9e in ???
> #6  0x7feb75819d0c in ???
> #7  0x7feb75819e67 in ???
> #8  0x559600f9f836 in __case_MOD_case_init
>         at /tmp/root/spack-stage/spack-stage-neko-0.6.1-r6n3ghz5aokgqhz2yry6ddsyeg3vcyhc/spack-src/src/case.f90:118
> #9  0x559601003dce in __neko_MOD_neko_init
>         at /tmp/root/spack-stage/spack-stage-neko-0.6.1-r6n3ghz5aokgqhz2yry6ddsyeg3vcyhc/spack-src/src/neko.f90:207
> #10  0x559601004f9d in turboneko
>         at /tmp/root/spack-stage/spack-stage-neko-0.6.1-r6n3ghz5aokgqhz2yry6ddsyeg3vcyhc/spack-src/src/driver.f90:6
> #11  0x559600eaa80e in main
>         at /tmp/root/spack-stage/spack-stage-neko-0.6.1-r6n3ghz5aokgqhz2yry6ddsyeg3vcyhc/spack-src/src/driver.f90:3
> ```

Since this is an old release, is the case file in the old namelist format?

**Comment by vbaconnet** [comment]
Oh yes it probably is :)

**Comment by njansson** [comment]
> Oh yes it probably is :)

Here's the file from 0.6.1
https://github.com/ExtremeFLOW/neko/blob/release/0.6/examples/2d_cylinder/2d_cylinder.case

**Comment by vbaconnet** [comment]
> Here's the file from 0.6.1 https://github.com/ExtremeFLOW/neko/blob/release/0.6/examples/2d_cylinder/2d_cylinder.case

Thanks, it's working now!

**Review by vbaconnet — APPROVED** [review]
Works on WIndows with WSL :+1:

**Pull request merged**
