### PR TITLE
Make brinkman fields private

### PR DESCRIPTION
**Pull request by timfelle**

### CODE REVIEW

**Review by njansson — APPROVED** [review]

**Comment by timfelle** [comment]
@njansson Seem like the MacOS machines are acting up. The linker complain about not having symbols for x86_64, are we sometimes compiling on arm chips with the MacOS?

**Comment by njansson** [comment]
> @njansson Seem like the MacOS machines are acting up. The linker complain about not having symbols for x86_64, are we sometimes compiling on arm chips with the MacOS?

I suspect this is something related to the home-brew packages. I do daily builds on macOS, both arm and x64

**Comment by timfelle** [comment]
> I suspect this is something related to the home-brew packages. I do daily builds on macOS, both arm and x64

Right, it was just since it's realated to jsonfortran which we compile manually.

**Comment by njansson** [comment]
> > I suspect this is something related to the home-brew packages. I do daily builds on macOS, both arm and x64
> 
> Right, it was just since it's realated to jsonfortran which we compile manually.

Let's flush the caches and see if it fixes the issue with a fresh build

**Comment by MartinKarp** [comment]
I got the same before and reran it and then those checked passed.

**Review by MartinKarp — APPROVED** [review]

**Pull request merged**
