### PR TITLE
Update map_to_equidistant_1d.f90

### PR DESCRIPTION
**Pull request by Shiyu-Sandy-Du**
Assign zero entries in the identity matrix explicitly.

### CODE REVIEW

**Comment by timofeymukha** [comment]
it's a tiny matrix, right? So you can just add `ident = 0.0_rp` right after allocation, which will assign everything to 0 from the beginning (or use `rzero` from `math.f90`, but I think it is kind of overkill). Then you can skip the do-loop and ifs you add here.

**Comment by Shiyu-Sandy-Du** [comment]
> it's a tiny matrix, right? So you can just add `ident = 0.0_rp` right after allocation, which will assign everything to 0 from the beginning (or use `rzero` from `math.f90`, but I think it is kind of overkill). Then you can skip the do-loop and ifs you add here.

Sure it's a better way. Code is changed now.

**Review by timofeymukha — APPROVED** [review]

**Comment by Shiyu-Sandy-Du** [comment]
The output had a bit bug and fixed now.

**Review by MartinKarp — APPROVED** [review]
Looks good

**Pull request merged**
