### PR TITLE
Module scope

### LINKED ISSUE #795: Module scope
Recent release of Cray Fortran (v15) exposes our sloppy module usage, throwing several warnings (`ftn-878`) about already associated modules in the same scope

### PR DESCRIPTION
**Pull request by njansson**
Restrict module scope to avoid indirect association in a scoping unit.

This removes most of the `ftn-878` warnings when compiling with `cce > 14` (#795)

### CODE REVIEW

**Comment by timofeymukha** [comment]
A much-needed update in terms of best practices, I guess. So, I discern two guidelines here.
1. Always have default scope as `private` in modules, forcing to explicitly declare what is `public.`
2. Directly declare what you need from a module with `only`. There are still imports that don't use this, though. For example, for `utils`, sometimes it is imported completely, and sometimes only concrete stuff. Is there some logic behind this?

So you know why the other compilers are complaining?

**Comment by timofeymukha** [comment]
> So far, I've only seen Cray throwing warnings about this, and I'm not sure what the standard says. But I still think it's good to fix these issues.

What I meant is why the CI is unhappy.

**Review by timofeymukha — APPROVED** [review]

**Comment by njansson** [comment]
> > So far, I've only seen Cray throwing warnings about this, and I'm not sure what the standard says. But I still think it's good to fix these issues.
> 
> What I meant is why the CI is unhappy.

Missing interfaces in certain backends, after `private` has been added.

**Comment by njansson** [comment]
Depends on #973 being merged

**Comment by njansson** [comment]
Depends on #974 being merged

**Comment by njansson** [comment]
Depends on #975 being merged

**Comment by njansson** [comment]
In the spirit of #794, almost types follows the same format (type-bound) such that redundant module use can be kept at a minimum

**Pull request merged**
