### PR TITLE
performance fix in gmres

### PR DESCRIPTION
**Pull request by pohm01**

### CODE REVIEW

**Review by njansson — APPROVED** [review]
Great stuff! 🍻 🐈

**Review by Shiyu-Sandy-Du — APPROVED** [review]

**Comment by njansson** [comment]
@timfelle Seems like we have another hickup with flinter preprocessed files, it will 💣 on `#endif` asking it to be expanded with a space like `#end if`

**Comment by timfelle** [comment]
> @timfelle Seems like we have another hickup with flinter preprocessed files, it will 💣 on `#endif` asking it to be expanded with a space like `#end if`

On it, tim mentioned it yesterday as well

**Comment by njansson** [comment]
> > @timfelle Seems like we have another hickup with flinter preprocessed files, it will 💣 on `#endif` asking it to be expanded with a space like `#end if`
> 
> On it, tim mentioned it yesterday as well. I'll bundle it with another cornercase he found that i haven't sorted just yet

🍺 🍻 🐈‍⬛

**Pull request merged**
