### PR TITLE
NEKO v0.8.0

### PR DESCRIPTION
**Pull request by njansson**

### CODE REVIEW

**Comment by timfelle** [comment]
I guess the new CI is not added in here. Is that the plan?

**Comment by njansson** [comment]
> I guess the new CI is not added in here. Is that the plan?

Good question. I guess it would be rather painful to cherry pick all changes

**Comment by timfelle** [comment]
> Good question. I guess it would be rather painful to cherry pick all changes

We can also just update the roccm version in a separate PR directly to the release and then wait for 0.8.1 with the CI

**Comment by njansson** [comment]
> > Good question. I guess it would be rather painful to cherry pick all changes
> 
> We can also just update the roccm version in a separate PR directly to the release and then wait for 0.8.1 with the CI

Sounds like an excellent compromise ;)

**Comment by MartinKarp** [comment]
How are we looking on this one? To me it looks good, there are of course things getting added all the time, but I think this is in a relatively good state to get merged and us having a more recent release.

**Review by MartinKarp — APPROVED** [review]

**Comment by njansson** [comment]
> How are we looking on this one? To me it looks good, there are of course things getting added all the time, but I think this is in a relatively good state to get merged and us having a more recent release.

Agree, I think this was also the conclusion at the latest dev meeting.

Let me fix the version number etc , and we focus on 0.9 instead

**Pull request merged**
