### PR TITLE
Added some implicit none

### PR DESCRIPTION
**Pull request by timofeymukha**
Took a few files and added implicit none to all procedures. Is that what we should aim for, or do we rely on propagation from module level? Somehow, I would like to have it everywhere.

### CODE REVIEW

**Comment by njansson** [comment]
All procedures within a module are in the same scope, thus `implicit none` in the module will cover everything.
Most of the files in this pr has `implicit none` in the module except `neko.f90`, where I guess there is a discussion if one should provide an implicit `implicit none` for each user or do it per subroutine.

**Comment by timofeymukha** [comment]
OK, so should we generally rely on module-level `implicit none`?

**Comment by njansson** [comment]
> OK, so should we generally rely on module-level `implicit none`?

Yes I would say so. The question is how to deal with interfaces, these are not covered by the `implicit none` under the modules scope.

**Comment by MartinKarp** [comment]
I also think it is enough with implicit none in the module.

**Comment by timofeymukha** [comment]
So perhaps to interfaces we need to add it explicitly. Although it is not that often one would create something there by accident.

**Pull request closed without merging**
