### PR TITLE
debug on projection

### PR DESCRIPTION
**Pull request by Shiyu-Sandy-Du**
debug projection to make simulation work without projection and remove some dummy stuffs

### CODE REVIEW

**Comment by timofeymukha** [comment]
A little bit sad to have the ifs back in the fluid step. Would it be a good trick to init the projections with activ_step=huge(0) when the space size is 0, or something like that, so that they just effectively never run?

**Comment by Shiyu-Sandy-Du** [comment]
> A little bit sad to have the ifs back in the fluid step. Would it be a good trick to init the projections with activ_step=huge(0) when the space size is 0, or something like that, so that they just effectively never run?

I have no idea, it sounds work, but those ifs are quite simple, right?

**Comment by njansson** [comment]
> > A little bit sad to have the ifs back in the fluid step. Would it be a good trick to init the projections with activ_step=huge(0) when the space size is 0, or something like that, so that they just effectively never run?
> 
> 
> 
> I have no idea, it sounds work, but those ifs are quite simple, right?

I tend to agree with @timofeymukha comments, nice to keep the step loop as clean as possible and hide the logic somewhere else

**Comment by Shiyu-Sandy-Du** [comment]
Ohhh actually we don't need to do anything, but remove the "if" in the constructor of objects. In pre and post-solving projection subroutine, all processing start only if this%L .gt. 0

**Review by njansson — APPROVED** [review]

**Comment by njansson** [comment]
We need to fix this to address currently failed CI runs

**Pull request merged**
