### PR TITLE
Move factories to submodules

### PR DESCRIPTION
**Pull request by njansson**
Move factories to submodule under respective base type. Avoids circular dependencies, reduces use statements and compilation deps

### CODE REVIEW

**Review by timfelle — COMMENTED** [review]
Looks really good. It seem like a great way of doing this.

**Comment by njansson** [comment]
Clean build with fj, so I would suggest we proceed with this once CI is happy

**Comment by adperezm** [comment]
May I ask, does this one affect OIF? One should try to get that in, no? It seems this one here touches a lot of files.

**Comment by njansson** [comment]
> May I ask, does this one affect OIF? One should try to get that in, no? It seems this one here touches a lot of files.

Good point. 

These submodules will make that cleanup less painful

**Pull request merged**
