### PR TITLE
Flint updates

### PR DESCRIPTION
**Pull request by timfelle**
This is to track updates and corner cases to flint.

Continual improvements can be added. If a breaking bug is found we fix it here and mark it ready for review.

- [x] Trailing whitespace trigged if last line of file was not empty.
- [x] Line breaks bypassed the bracket usage rule.
- [x] Spaces arround `::` triggered inside allocation.
- [x] Punctuation spacing rule triggered by format strings with double quotes.
- [x] Punctuation spacing rule should always apply to opening paranthesis and strings
- [x] False activation of assignment spacing rule
	  Example: `character(kind=c_char, len=8192), target :: prop`
- [x] Max line number triggered already at 1247 lines in device.f90.

Skipped so far:
- [ ] Double spaces should be allowed inside strings.
- [ ] Comment spacing rule triggered in strings ended with line breaks.

### CODE REVIEW

**Review by timfelle — COMMENTED** [review]
I'll try to test this, hence the conversion from "draft" to "don't merge"

**Review by timfelle — COMMENTED** [review]
It seems like some strange inlining happens.
I do not understand how the worst function can be the `is`-statements, and that it looks like `device_memcpy_r1` calls `device_memcpy_r2` after two layers of `is` recursion.
```
Worst rated files:
  src/flinter_dummy_file.f90: 9.84
Worst rated functions:
  src/flinter_dummy_file.f90/device/device_memcpy_r1: 9.81
  src/flinter_dummy_file.f90/device: 9.83
  src/flinter_dummy_file.f90/device/device_memcpy_r1/is/is/device_memcpy_r2: 9.85
  src/flinter_dummy_file.f90/device/device_memcpy_r1/is/is: 9.85
  src/flinter_dummy_file.f90/device/device_memcpy_r1/is: 9.85
```

**Review by timfelle — COMMENTED** [review]
> It seems like some strange inlining happens.
I do not understand how the worst function can be the `is`-statements, and that it looks like `device_memcpy_r1` calls `device_memcpy_r2` after two layers of `is` recursion.
```
Worst rated files:
  src/flinter_dummy_file.f90: 9.84
Worst rated functions:
  src/flinter_dummy_file.f90/device/device_memcpy_r1: 9.81
  src/flinter_dummy_file.f90/device: 9.83
  src/flinter_dummy_file.f90/device/device_memcpy_r1/is/is/device_memcpy_r2: 9.85
  src/flinter_dummy_file.f90/device/device_memcpy_r1/is/is: 9.85
  src/flinter_dummy_file.f90/device/device_memcpy_r1/is: 9.85
``` 

Solved, it was the context limit and not line limit.

**Review by njansson — APPROVED** [review]
🍻

**Review by pohm01 — APPROVED** [review]
Ltgm

**Comment by timfelle** [comment]
@njansson Apparently auto merge is off at the moment.

**Pull request merged**
