### PR TITLE
Pass error codes to `error stop` statements

### PR DESCRIPTION
**Pull request by timfelle**

### CODE REVIEW

**Review by njansson — APPROVED** [review]

**Comment by timfelle** [comment]
@njansson Do we only support Fortran 2003 and not Fortran 2008?

**Comment by njansson** [comment]
> @njansson Do we only support Fortran 2003 and not Fortran 2008?

We require at least Fortran 2008

**Comment by timfelle** [comment]
> > @njansson Do we only support Fortran 2003 and not Fortran 2008?
> 
> We require at least Fortran 2008

Interesting, our CI gets compiled to 2003, as support for the feature i tried to implement here is fortran 2008 and the error message indicate support only ranging for the 2003 features.

https://stackoverflow.com/a/17446997

**Comment by njansson** [comment]
> > > @njansson Do we only support Fortran 2003 and not Fortran 2008?
> > 
> > 
> > We require at least Fortran 2008
> 
> Interesting, our CI gets compiled to 2003, as support for the feature i tried to implement here is fortran 2008 and the error message indicate support only ranging for the 2003 features.
> 
> https://stackoverflow.com/a/17446997

I think the issue for the CI is the non constant error message

**Comment by timfelle** [comment]
> I think the issue for the CI is the non constant error message

Riiight, we do not always call the function with a constant error message.

**Review by timofeymukha — APPROVED** [review]

**Comment by timfelle** [comment]
Interesting it would seem my local compiler succeeds since because it compiles to Fortran 2018 and not Fortran 2008. This use is not allowed in Fortran 2008.

**Pull request closed without merging**
