### PR TITLE
Add linting action and create post merge job for develop

### PR DESCRIPTION
**Pull request by timfelle**
This pull request adds a linting action to execute the Flint linter on the specified directory. It also creates a post merge job for the develop branch that runs compilation checks and creates badges based on the results. Additionally, the badges for the linting score and compiler support are used to show the status of the code.

At the moment, the post merge job on develop should trigger whenever a PR is merged into develop succesfully.
Alternatively we can let it run as part of the nightly documentation update, this could be part of a nightly release job.

### CODE REVIEW

**Comment by timofeymukha** [comment]
Cool, badges are nice :-)

**Review by njansson — APPROVED** [review]

**Comment by timofeymukha** [comment]
Aren't things guaranteed to compile right after a merge, if CI greenlights it?

**Comment by timfelle** [comment]
Btw, the linting job for this one cannot complete, since i created a new action. The workflow will run the action from develop, but develop does not have the action yet.

**Comment by timfelle** [comment]
> Aren't things guaranteed to compile right after a merge, if CI greenlights it?

Well we recently broke NVfortran, but otherwise yes

**Comment by timofeymukha** [comment]
I see. So it is more to just show the status of what we got rather than to check for unexpected failures.

**Review by timofeymukha — APPROVED** [review]

**Comment by timfelle** [comment]
It would be nice if we could avoid the full retest though 🤔

**Comment by timofeymukha** [comment]
I would say in the long run it is better to do it nightly, then it doesn't really matter if it takes a bit of time.

**Pull request merged**
