### PR TITLE
Fix invalid module dependencies

### PR DESCRIPTION
**Pull request by njansson**

### CODE REVIEW

**Review by timfelle — COMMENTED** [review]
Linter is broken for allocation statements with "::". It always triggers it seems. Issue #1405 have been updated to track the issue

**Review by timofeymukha — APPROVED** [review]

**Comment by timfelle** [comment]
I guess `json_file` is no longer implicitly made available when asking for `use neko`. Do we want to fix it by explicitly adding `use json_module, only: json_file` to `neko.f90` or do we wish that users ask for the json library manually since it is an external dependency?

**Comment by njansson** [comment]
> I guess `json_file` is no longer implicitly made available when asking for `use neko`. Do we want to fix it by explicitly adding `use json_module, only: json_file` to `neko.f90` or do we wish that users ask for the json library manually since it is an external dependency?

I think the best would be in neko, such that we minimize the amount of boilerplate code for users of the user interface

**Review by timfelle — APPROVED** [review]
Well I guess you might want to manually merge this to avoid all the missing only statements in `neko.f90`

**Pull request merged**
