### PR TITLE
Add full axhelm cpu kernels and cg_stress

### PR DESCRIPTION
**Pull request by timofeymukha**
I hope the history got preserved, but I am not sure. Jumped a lot of hoops with `git mv` and merging.

### CODE REVIEW

**Comment by njansson** [comment]
For the history to be preserved I think we need to merge the stress branch instead. Shouldn't we just do that? What can go wrong ;)

**Comment by timofeymukha** [comment]
@njansson But this is cherry-picked from that branch I think. Shouldn't it be the same?

**Comment by njansson** [comment]
> @njansson But this is cherry-picked from that branch I think. Shouldn't it be the same?

Don't think so, it doesn't look like a `git cherry-pick`, or is it?

**Review by timfelle — APPROVED** [review]

**Comment by timfelle** [comment]
@timofeymukha This PR is too old to have the new CI. It needs to brought up to date with develop.

**Comment by timofeymukha** [comment]
It seems I will be the flint guinea pig

**Comment by timfelle** [comment]
> It seems I will be the flint guinea pig

I guess so 😅 Let me know if you feel its easy enough to read the feedback you get from the CI. We can try to make it clearer if needed.

**Comment by timofeymukha** [comment]
One issue seems to be that the line number are off.

**Comment by timfelle** [comment]
Yes i have noticed that, but I haven't narrowed down what causes it, because its not all files. Flint seem to do some preprocessing on some of the files.

**Comment by timofeymukha** [comment]
What is exepcted here?
```
missing-space-before-parenthesis
+---------+--------+------+------------------------+
| line_no | column | span |          line          |
+---------+--------+------+------------------------+
|    76   |   11   |  5   |     select case(Xh%lx) |
|    77   |   4    |  5   |          case(14)      |
|    83   |   4    |  5   |          case(13)      |
|    89   |   4    |  5   |          case(12)      |
|    95   |   4    |  5   |          case(11)      |
|   101   |   4    |  5   |          case(10)      |
|   107   |   4    |  5   |          case(9)       |
|   113   |   4    |  5   |          case(8)       |
|   119   |   4    |  5   |          case(7)       |
|   125   |   4    |  5   |          case(6)       |
|   131   |   4    |  5   |          case(5)       |
|   137   |   4    |  5   |          case(4)       |
|   143   |   4    |  5   |          case(3)       |
|   149   |   4    |  5   |          case(2)       |
+---------+--------+------+------------------------+
```

**Comment by njansson** [comment]
> Yes i have noticed that, but I haven't narrowed down what causes it, because its not all files. Flint seem to do some preprocessing on some of the files.

We can of course always ask the flint developers (@dauptaia), they might be interested in what kind of monster you have created @timfelle

**Comment by timfelle** [comment]
> What is exepcted here?
> 
> ```
> missing-space-before-parenthesis
> +---------+--------+------+------------------------+
> | line_no | column | span |          line          |
> +---------+--------+------+------------------------+
> |    76   |   11   |  5   |     select case(Xh%lx) |
> |    77   |   4    |  5   |          case(14)      |
> |    83   |   4    |  5   |          case(13)      |
> |    89   |   4    |  5   |          case(12)      |
> |    95   |   4    |  5   |          case(11)      |
> |   101   |   4    |  5   |          case(10)      |
> |   107   |   4    |  5   |          case(9)       |
> |   113   |   4    |  5   |          case(8)       |
> |   119   |   4    |  5   |          case(7)       |
> |   125   |   4    |  5   |          case(6)       |
> |   131   |   4    |  5   |          case(5)       |
> |   137   |   4    |  5   |          case(4)       |
> |   143   |   4    |  5   |          case(3)       |
> |   149   |   4    |  5   |          case(2)       |
> +---------+--------+------+------------------------+
> ```

`case(2)` -> `case (2)`

**Comment by timfelle** [comment]
> > Yes i have noticed that, but I haven't narrowed down what causes it, because its not all files. Flint seem to do some preprocessing on some of the files.
> 
> We can of course always ask the flint developers (@dauptaia), they might be interested in what kind of monster you have created @timfelle

I guess this will catch all kinds of edge cases in the long run yes 😅

**Comment by timofeymukha** [comment]
And is this table about the space after the comma in the array indices?
```
missing-spaces-after-punctuation
+---------+--------+------+---------------------------------------------------------+
| line_no | column | span |                           line                          |
+---------+--------+------+---------------------------------------------------------+
|   194   |   38   |  3   |            real(kind=rp), intent(in) :: Dx(lx,lx)       |
```

**Comment by timfelle** [comment]
> And is this table about the space after the comma in the array indices?
> 
> ```
> missing-spaces-after-punctuation
> +---------+--------+------+---------------------------------------------------------+
> | line_no | column | span |                           line                          |
> +---------+--------+------+---------------------------------------------------------+
> |   194   |   38   |  3   |            real(kind=rp), intent(in) :: Dx(lx,lx)       |
> ```

Well, it looks for commas in this case, so it should be `Dx(lx, lx)`.

**Comment by njansson** [comment]
> And is this table about the space after the comma in the array indices?
> 
> ```
> missing-spaces-after-punctuation
> +---------+--------+------+---------------------------------------------------------+
> | line_no | column | span |                           line                          |
> +---------+--------+------+---------------------------------------------------------+
> |   194   |   38   |  3   |            real(kind=rp), intent(in) :: Dx(lx,lx)       |
> ```

Ok, we probably have to slaughter tons of kittens to get ax_helm like code in with the new linter 😿

**Comment by timofeymukha** [comment]
Fixing the declarations is not an issue, but in the part doing computations we have a lot of (i,j,k,e) stuff with no comma. But didn't we agree to allow that?

**Comment by njansson** [comment]
> Fixing the declarations is not an issue, but in the part doing computations we have a lot of (i,j,k,e) stuff with no comma. But didn't we agree to allow that?

Hear! Hear!

**Comment by timfelle** [comment]
> > Fixing the declarations is not an issue, but in the part doing computations we have a lot of (i,j,k,e) stuff with no comma. But didn't we agree to allow that?
> 
> Hear! Hear!

Yes, we allow a comma followed by a single character. If you look closely you will find that all lines flagged have a `10`, `11` or similar in that line

**Pull request merged**
