### PR TITLE
Fused CG for CUDA/HIP

### PR DESCRIPTION
**Pull request by njansson**
This adds the fused CG formulation for accelerators (currently limited to CUDA/HIP), with minimal data movement H2D during iterations.

### CODE REVIEW

**Comment by timofeymukha** [comment]
A bit confused: is this a new type of solver, or is this somehow a fusion of codes for 2 types of accelerators into one?

**Comment by njansson** [comment]
> A bit confused: is this a new type of solver, or is this somehow a fusion of codes for 2 types of accelerators into one?

Same solver, just another version with a different optimisation strategy, kernel fusing (fewer large ones), more similar to our current CPU implementation, and more accelerator friendly. However, we should probably not replace our current `cg_device`, under certain circumstances, the many small kernels, can easier be overlapped in `hsmg`

In short, see it as yet an alternative CG, as pipelined, enabled by `fusedcg` in the case file

**Comment by timofeymukha** [comment]
I see, great stuff. So it is selectable from the case file then? If so, please add it to the case-file.md docs! Ideally, with some minimal guideline on when to select it.

**Comment by njansson** [comment]
> I see, great stuff. So it is selectable from the case file then? If so, please add it to the case-file.md docs! Ideally, with some minimal guideline on when to select it.

Fair enough, always forgets about the documentation (T_T)

**Review by timofeymukha — APPROVED** [review]

**Review by MartinKarp — APPROVED** [review]

**Pull request merged**
