### PR TITLE
Add built-in profiler

### PR DESCRIPTION
**Pull request by timfelle**
Addition of a built in profiler which will report the global cpu-time and evaluation count.

The new profiler is disabled by default and can be turned on by setting `--enable-profiling` when configuring Neko.

### CODE REVIEW

**Comment by timofeymukha** [comment]
Is this related to #1067 ?

**Comment by timfelle** [comment]
> Is this related to #1067 ?

I had no idea that PR existed. Just just wanted to measure time so i expanded the existing profiler to run without a separate backend.

**Comment by timfelle** [comment]
@timofeymukha and @njansson Should we close this or do you think some of this approach could be useful in the other PR?

**Comment by timfelle** [comment]
Should we kill this PR @njansson?

**Comment by timfelle** [comment]
Superseded by PR #1467

**Pull request closed without merging**
