### PR TITLE
Fix segfault for rea2nbin

### PR DESCRIPTION
**Pull request by MartinKarp**
Rea2nbin segfaults for meshes with combination of labeled zones and periodic bcs. Also adds support for EXO labels in the mesh.

### CODE REVIEW

**Comment by timfelle** [comment]
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f23bbdb1960 in ???
#1  0x7f23bbdb0ac5 in ???
#2  0x7f23bbaa051f in ???
	at ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
#3  0x7f23bbbfe815 in ???
	at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:383
#4  0x7f23bc01328e in ???
#5  0x7f23bc0142e5 in ???
#6  0x5642fabc504d in re2_file_read_bcs
	at io/re2_file.f90:687
#7  0x5642fabc6362 in __re2_file_MOD_re2_file_read
	at io/re2_file.f90:196
#8  0x5642fabaa428 in __file_MOD_file_read
	at io/file.f90:163
#9  0x5642fab94fdd in rea2nbin
	at /home/tife/Projects/neko-top/external/neko/contrib/rea2nbin/rea2nbin.f90:38
#10  0x5642fab94ade in main
	at /home/tife/Projects/neko-top/external/neko/contrib/rea2nbin/rea2nbin.f90:2
```

**Comment by timfelle** [comment]
A simple pipe generated in Cubit and converted from .exo to .re2 by Nek5000.

**Comment by timfelle** [comment]
[debugging_pipe.re2.log](https://github.com/user-attachments/files/17129755/debugging_pipe.re2.log)
Remove the .log to recover the re2 file

**Comment by MartinKarp** [comment]
Not tried that, if you could share that it would be great. This seems to fix gmsh-re2-nmsh at least. How longs has this been going on?

**Comment by MartinKarp** [comment]
For EXO one should get the warning that the bc is not supported, but instead one segfaults. Im checking what I can fix quick.

**Comment by MartinKarp** [comment]
OKay, I have found the bug.

**Comment by MartinKarp** [comment]
Should be fixed now. I guess the mesh you shared is supposed to be a duct?

**Comment by MartinKarp** [comment]
Tested it with the case file for turbpipe with mesh: debugging_pipe.nmsh and "boundary_types": ["v", "o", "w", "sym"]

**Comment by timfelle** [comment]
> Should be fixed now. I guess the mesh you shared is supposed to be a duct?

Yes yes, duct not pipe 😅

**Comment by timfelle** [comment]
I just ran it as well and it seem to be fixed here as well now

**Review by timfelle — APPROVED** [review]

**Comment by vbaconnet** [comment]
Thanks for fixing my mess :D

**Review by vbaconnet — APPROVED** [review]

**Pull request merged**
